apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-pipeline-config
spec:
  params:
    - name: project-name
      description: The Project Name from the Config
      type: string
    - name: project-type
      description: The Project type from the Config
      type: string
    - name: build-main
      description: Parameter for Build main Repo image
      type: string
    - name: build-tests
      description: Parameter for Build tests Repo image
      type: string
    - name: gitops-url
      description: the GitOps repo Full URL
      type: string
    - name: gitops-applicationpath
      description: the GitOps repo application Path
      type: string
  steps:
    - name: get-results-from-pipeline
      image: 'quay.io/thason/pipeline-tools:latest'
      args:
        - '-c'
        - >
          set -x

          echo "The Project Name from the Config: $(params.project-name)"

          echo "The Project type from the Config: $(params.project-type)"
          
          echo "Parameter for Build main Repo image: $(params.build-main)"

          echo "Parameter for Build tests Repo image: $(params.build-tests)"

          echo "the GitOps repo Full URL: $(params.gitops-url)"

          echo "the GitOps repo application Path: $(params.gitops-applicationpath)"

      command:
        - /bin/bash
      resources: {}
