apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-with-results
spec:
  destination:
    namespace: tekton-with-results
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: Setup
    repoURL: 'https://github.com/tal-hason/tekton-pipeline-with-result.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

